# .github/workflows/publish-plugin.yml
name: Publish Windy Plugin

# Run on every push to main, or manually in the Actions UI
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # 1. Check out your code
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2. Set up Node (for the Svelte build)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # 3. Build your Windy plugin
      - name: Build Windy plugin
        working-directory: knmi-windy-plugin
        run: |
          npm install
          npm run build

      # 4. Publish to Windy’s plugin registry
      - name: Publish to Windy
        uses: windycom/publish-plugin-action@v1
        with:
          apiKey: ${{ secrets.WINDY_API_KEY }}
          # relative path from repo root to the built plugin folder
          pluginDistDir: knmi-windy-plugin/dist
          # a unique plugin slug (must start with "windy-plugin-")
          pluginName: windy-plugin-knmi-qg-regions
          # semver version; bump this to trigger a new release
          version: 0.1.0
