name: Publish Windy Plugin

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      WINDY_API_KEY: ${{ secrets.WINDY_API_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: knmi-windy-plugin
        run: npm ci

      - name: Build plugin bundle
        working-directory: knmi-windy-plugin
        run: npm run build

      - name: Publish to Windy
        working-directory: knmi-windy-plugin/dist
        run: |
          if [ -z "$WINDY_API_KEY" ]; then
            echo "Secret WINDY_API_KEY is not configured" >&2
            exit 1
          fi

          echo "Embedding repository metadata..."
          cat <<'JSON' > /tmp/plugin-info.json
          {
            "repositoryName": "${{ github.repository }}",
            "commitSha": "${{ github.sha }}",
            "repositoryOwner": "${{ github.repository_owner }}"
          }
          JSON

          mv plugin.json /tmp/plugin.json.orig
          jq -s '.[0] * .[1]' /tmp/plugin.json.orig /tmp/plugin-info.json > plugin.json

          echo "Packaging plugin..."
          tar cf ../plugin.tar .

          echo "Uploading to Windy..."
          curl -sS --fail-with-body \
            -X POST 'https://node.windy.com/plugins/v1.0/upload' \
            -H "x-windy-api-key: ${WINDY_API_KEY}" \
            -F "plugin_archive=@../plugin.tar"

      - name: Reminder
        run: |
          echo "::notice ::Upload complete. The Windy API responded above with a JSON payload containing the installation URL."
