name: Update KNMI QG GeoJSON

on:
  schedule:
    - cron: "*/10 * * * *"  # every 10 minutes
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest
    env:
      KNMI_API_KEY: ${{ secrets.KNMI_API_KEY }}
      GITHUB_PAT: ${{ secrets.REPO_UPLOAD_TOKEN }}
      REGIONS_FILE: data/regions_10.geojson
      OUTPUT_FILE: qg_regions.geojson
      HISTORY_FILE: qg_regions_history.geojson
      STATIONS_FILE: stations_live.geojson
      STATION_HISTORY_JSON: knmi_station_data/station_metrics_history.json
      STATION_HISTORY_GEOJSON: knmi_station_data/station_metrics_history.geojson
      REPO_SLUG: artis-byte/NL-solar
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install h5netcdf

      - name: Generate latest QG GeoJSON
        run: |
          if [ -z "$KNMI_API_KEY" ]; then
            echo "::error::Secret KNMI_API_KEY is not configured"
            exit 1
          fi
          if [ -z "$GITHUB_PAT" ]; then
            echo "::error::Secret REPO_UPLOAD_TOKEN is not configured"
            exit 1
          fi

          python src/knmi_qg_regions.py \
            --api-key "$KNMI_API_KEY" \
            --regions "$REGIONS_FILE" \
            --out "$OUTPUT_FILE" \
            --history-out "$HISTORY_FILE" \
            --stations-out "$STATIONS_FILE" \
            --gh-repo "$REPO_SLUG" \
            --gh-path "$OUTPUT_FILE" \
            --gh-history-path "$HISTORY_FILE" \
            --gh-stations-path "$STATIONS_FILE" \
            --station-history-json "$STATION_HISTORY_JSON" \
            --station-history-geojson "$STATION_HISTORY_GEOJSON" \
            --gh-station-history-path "$STATION_HISTORY_GEOJSON" \
            --gh-branch main \
            --gh-token "$GITHUB_PAT"
